# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
ew_subtraction = B - C
print(ew_subtraction)
ew_multiplication = B * C
print(ew_multiplication)
matrix_multiply = B @ C
print(matrix_multiply)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [36]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

print(np.exp(B))
print(np.min(B))
print(np.min(B, axis=1))
print(np.min(B, axis=0))
print(np.argmin(B))
print(np.argmin(B, axis=1))
print(np.sum(B))
print(np.mean(B, axis=0))
print(np.median(B, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
Output man får är den andra raden (index 1) i en 2D array. Det finns två axis i array:n, (rad och kolumn),
men när man inte skriver kod för en specifik punkt, så tolkar Numpy det att du kör en slice genom hela raden, inklusive alla kolumner.
Vill man ha en mer specifik punkt för en kolumn kan lägga till det med exempelvis: A[1, 2].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [37]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [41]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [40]:
Svar:
.arange(30) genererar nummer i en sekvens, mellan 0 - 29. (Börjar från 0), i en 1 dimensionell array. 
.reshape ändrar den till en ny array med en specifik definierad shape. I detta fallet 2, 3. (Första axis = 2, andra = 3)
Men i tredje axis (-1), säger man till NumPy att automatiskt kalkylera storleken för denna axis, baserad på den totala mängden element (30).
Detta skapar en 3 dimensionell array med 2 block (första axis), 3 rader (andra axis), och 5 element för varje rad (eftersom totala mängden element är 30).

Side note: Som jag förstått det, så baseras den reshaped arrayn 5 element för varje rad. Är det korrekt att då säga att den tredje axis (-1, som blir 5 efter reshape), skapar 5 kolumner?

SyntaxError: invalid syntax (2383973643.py, line 1)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [42]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [43]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [44]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [94]:
import numpy as np

In [48]:
matrix1 = np.array([1, 2, 3, 4, 5]).reshape(1, 5)
matrix2 = np.array([6, 7, 8, 9, 10]).reshape(5, 1)

def add_mult_matrices(matrix1, matrix2, add_or_multiply):
    
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        print("Type is not .ndarray")
        return None
    
    if add_or_multiply == 'add':
        if matrix1.shape[1] != matrix2.shape[0]:
            print("Shape mismatch")
            return None
        return matrix1 + matrix2
    
    elif add_or_multiply == 'multi':
        if matrix1.shape[1] != matrix2.shape[0]:
            print("Shape mismatch")
            return None
        return np.dot(matrix1, matrix2)
    
    else:
        print("'Add' or 'Multiply'")
        return None
        
add = add_mult_matrices(matrix1, matrix2, "add")
multi = add_mult_matrices(matrix1, matrix2, "multi")

print(add)
print(multi)


[[ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]
 [10 11 12 13 14]
 [11 12 13 14 15]]
[[130]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [19]:
x = np.array([4, 3]) # 1D Array
x_re = np.array([4, 3]).reshape(2, 1) # 2D Array

# a)
print(x.shape) # 1D Array
print(x_re.shape) # 2D array

# b)
print(5 * x)

# c)
print(3 * x)

# d)
print(5 * x + 3 * x)

# e)
print(8 * x)

# f)
print(4 * x - x)

# g)
# Om x är definierat som en 1D array
print(x.T.shape)

# Om x är definierat som en 2D array
print(x_re.T.shape)

# h)
x_t = (x.T)
print(x + x_t)

# i)
print(np.linalg.norm(x))
print(np.linalg.norm(x_re))


(2,)
(2, 1)
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
(2,)
(1, 2)
[8 6]
5.0
5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [58]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])


a = 2 * A
print(a)

b = B - 2 * A
print("\n", b)

c = 3 * C - 2 * E
print("\n", c)

d = 2 * D - 3 * C
print("\n", d)

e = D.T + 2 * D
print("\n", e)

f = 2 * C.T - 2 * D.T
print("\n", f)

#g = A.T - B - "ValueError: operands could not be broadcast together with shapes (3,2) (2,3)"
#print("\n", g)

h = add_mult_matrices(A, C, "multi")
print("\n", h)

i = add_mult_matrices(C, D, "multi")
print("\n", i)

j = add_mult_matrices(C, B, "multi")
print("\n", j)

k = add_mult_matrices(C, I, "multi")
print("\n", k)

i = add_mult_matrices(A, B.T, "multi")
print("\n", i)



[[ 4  2 -2]
 [ 2 -2  2]]

 [[ 0 -4  3]
 [ 0 -2 -4]]

 [[ 1  4]
 [ 2 -1]]

 [[3 2]
 [2 3]]

 [[ 9 12]
 [12  9]]

 [[-4 -4]
 [-4 -4]]
Shape mismatch

 None

 [[11 10]
 [10 11]]

 [[  8 -10  -3]
 [ 10  -8   0]]

 [[1 2]
 [2 1]]

 [[5 2]
 [7 4]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

In [61]:
A = np.array([[2, 3, 4], [5, 4, 1]])

a = add_mult_matrices(A, A.T, "multi")
print(a)

[[29 26]
 [26 42]]


In [65]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

A_B = add_mult_matrices(A, B, "multi")
A_C = add_mult_matrices(A, C, "multi")

#Kollar att AB == AC
AB_AC = A_B == A_C
print(AB_AC)

#Kollar att B inte är lika med C
B_C = B != C
print("\n", B_C)

[[ True  True]
 [ True  True]]

 [[ True  True]
 [ True  True]]


**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [45]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [46]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [47]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
